### ISSUE TITLE
SCHILDEPARK_FENSTERPARADIES textures not installed via ModManFX

### ISSUE THREAD

**Issue by AndreGeddert** [christophjurczyk/MSFS2020_EDEN_Bad_Hersfeld_Scenery#1]
First of all thank you very much for your work.

When installing the v1.0.0 release with ModManFX 1.1.0.0 the installation status is "partially" and it seems that textures SCHILDEPARK_FENSTERPARADIES_TEXTURE_[0-6]_PNG.DDS.json files are not installed.

My first guess is that it has something to do with the lenght of the filenames, because these are the longest filenames in the package.

![EDEN_ModManFX](https://user-images.githubusercontent.com/6795099/91638788-2b994f80-ea12-11ea-8cd3-f62d67e65a2e.png)

**Comment by christophjurczyk** [comment]
Hi,
Happy to hear that some are interested in my scenery. 

I will check this on my setup and probably shorten the file name.

-Christoph

**Comment by christophjurczyk** [comment]
Hi, 
I checked it on my computer. ModManFX is not returning any warning or error on my simulator. Unfortunately, my path is a little bit different. Your path is `E:\Games\FS2020\Packages\Community\` my community folder is located under `F:\MSFS_2020\Community`

But anyhow your paths are less than the maximum allowed path length (260 characters). For example the following path has only 198 characters:
`E:\Games\FS2020\Packages\Community\MSFS2020_EDEN_Bad_Hersfeld_Scenery-1.0.0\cjscenery-scenery-eden-bad-hersfeld-rotenburg\scenery\global\scenery\TEXTURE\SCHILDEPARK_FENSTERPARADIES_TEXTURE_0.PNG.DDS`

I will shorten in the next version the file names. Until then you can try to remove the folder "MSFS2020_EDEN_Bad_Hersfeld_Scenery-1.0.0" in your path to shorten path.

-Christoph

**Comment by christophjurczyk** [comment]
Shorten file name in new release ([/releases/v1.1.0](https://github.com/christophjurczyk/MSFS2020_EDEN_Bad_Hersfeld_Scenery/releases/tag/v1.1.0)). Hope this solves your issue.
-Christoph

**Comment by AndreGeddert** [comment]
Thank you. New textures with short filesnames got installed by ModManFX now, but old files are still present in repository. Maybe delete them :)
