### ISSUE TITLE
Windsock is 180 Degrees from Wind

### ISSUE THREAD

**Issue by Lemit4001** [christophjurczyk/MSFS2020_EDEN_Bad_Hersfeld_Scenery#2]
Originally thought to be an MSFS 2020 bug, the problem was linked to this great scenery. (I love this airport.)

Weather page and Garmin 1000 showing wind as 30 degrees at 4 kts with the wind vector pointing towards 210.  (Wind out of 030 blowing towards 210 degrees.   Windsock 'mouth' is facing 210 and tail is facing 030.  Removed scenery and windsock indicates correctly.  I believe the windsock needs to be rotated.   See picture. The mouth of the windsock should be facing the opposite direction. 
![FlightSimulator 2020-10-13 14-27-48](https://user-images.githubusercontent.com/72827133/95918178-5698f200-0d79-11eb-9862-310d26ffd18b.png)

**Comment by christophjurczyk** [comment]
Hi, 
Thanks for the advice. I agree on this issue. Some months ago it seems that there was a bug in the standard windsock object, that's why I rotated the windsock by 180°. This seems to have been fixed. I will change it in the next release.
-Christoph

**Comment by Lemit4001** [comment]
People told me that this was caused by the error in MSFS that you
mentioned.  Seems it caught a lot of people.  I want you to know that I was
not complaining.  This is one of my favorite scenery add ons, and I thought
you would fix it if i brought it to your attention.    Your hard work has
made Bad Hersfeld a popular ace to fly in MSFS.

**Comment by christophjurczyk** [comment]
Fixed in v1.20
