### ISSUE TITLE
Interference with Powerlines and Solar Farms mod

### ISSUE THREAD

**Issue by HomieFFM** [christophjurczyk/MSFS2020_EDEN_Bad_Hersfeld_Scenery#3]
there is an interference on EDEN with the [Powerlines and Solar Farms](https://flightsim.to/file/26186/powerlines-and-solar-farms) mod.
possible solution would be exclusion-rectangles under your solar panels.

With a correct order in the content.xml both sceneries can live side by side 
and we can keep your much more detailed and nicely made solar panels on the airport :)

**Comment by christophjurczyk** [comment]
Thanks for info. I will add in the next release an exclusion-rectangle. Do the panels at Amazon FRA3 interfere as well?

**Comment by HomieFFM** [comment]
![1](https://user-images.githubusercontent.com/103950863/164072468-8043c744-1c94-4f9a-aa5d-89d8091630f4.jpg)
![2](https://user-images.githubusercontent.com/103950863/164072472-d135b13e-5539-4a43-b5e6-4a3114f73785.jpg)
![3](https://user-images.githubusercontent.com/103950863/164072477-7aee98a6-f824-4830-9a26-582222cf9063.jpg)

Yes, the Amazon building is also affected (the roof is ok, only the ones next to the building).
Thank you very much for your work :)

**Comment by HomieFFM** [comment]
Scenery Editor:

    We now allow real time editing for exclusion rectangles.

With that it should be even easier to get your solar panels exclusive :)

**Comment by HomieFFM** [comment]
I corrected it myself, if you want the updated version let me know.

**Comment by christophjurczyk** [comment]
Added exclusions in v1.20
